### ISSUE TITLE
Account Page - textovervlow email field

### ISSUE THREAD

**Issue by Bckstage** [komcommy/HAN-G42-EenmaalAndermaal#1]
Op de accountpagina in het stuk 'Mijn gegevens' gaan lange teksten buiten de kaders. Svp safeguard / limit instellen.

**Comment by Besselking** [comment]
- [x] user data

- [x] biedingen en veilingen

**Comment by Besselking** [comment]
misschien een beetje lelijk met de scrollbars, maar nu heb je tenminste geen overlappende text meer
