### ISSUE TITLE
Navbar - Aanmaken nieuwe bieding

### ISSUE THREAD

**Issue by Bckstage** [komcommy/HAN-G42-EenmaalAndermaal#2]
In de navbar is het aanmaken van een nieuwe bieding zichtbaar voor alle aangemelde gebruikers, deze afschermen dat alleen Merchants die kunnen zien en ook in de file zelf aangeven dat alleen merchants recht hebben om die gegevens te zien / aan te passen / te benaderen (kan doormiddel van een IF statement, ELSE return home)

**Comment by Besselking** [comment]
woops ik zag niet dat je al geassigned was
