### ISSUE TITLE
New product: Naamgeving invoervelden

### ISSUE THREAD

**Issue by Bckstage** [komcommy/HAN-G42-EenmaalAndermaal#5]
Controleer naamgeving invoervelden op consistentie.
**OF** gebruik alles **MET** dubbele punt. Of zonder. Maar niet allebei.
"Betaalmethode" aanpassen naar "Verzenden of ophalen" met de volgende opties:
- Ophalen
- Verzenden
- Ophalen & verzenden

Wij verwerken als website geen betalingen (los van de verificatie van een verkoper). Mits de Product Owner anders aangeeft.

**Comment by JurianB** [comment]
fixed <3
