### ISSUE TITLE
Nieuw product: Statusmeldingen in begrijpelijke taal

### ISSUE THREAD

**Issue by Bckstage** [komcommy/HAN-G42-EenmaalAndermaal#8]
Met de statusmelding: "Array ( [0] => 00000 [1] => [2] => ) Array ( [0] => 00000 [1] => [2] => )" kan niemand iets. Svp aanpassen naar iets simpels zoals "Succes" of een daadwerkelijke beschrijving wat er goed/fout is (als daar tijd voor is!).

**Comment by JurianB** [comment]
Foutmelding plaatsen advertentie gefixed
